### ISSUE TITLE
Intro Section Layout

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#1]
The formatting of the layout section seems off in many ways. Would putting the "Welcome" element and the "Announcement" elements side-by-side improve on this? Or should they maybe be more spread out?

**Comment by Amyffz** [comment]
zoom da thing bigger

**Comment by mcdoash** [comment]
Thing has been zoomed bigger:

<img width="1436" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28332945-6d97c0ee-6bc4-11e7-8ffa-1bbea0dd7342.png">

**Comment by Amyffz** [comment]
can you add a coloured box behind welcome to ccc? like it could be white on yellow or something?

**Comment by mcdoash** [comment]
Like this???

<img width="925" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28425087-4b6fafca-6d3d-11e7-9e91-63a4e95e3a8b.png">
<img width="925" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28425334-f600c50a-6d3d-11e7-870d-4d4ed6fc47a9.png">

**Comment by Amyffz** [comment]
Yeah, but don't change the message board thing
On Jul 20, 2017, at 11:24 AM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Like this???

[central_programming]<https://user-images.githubusercontent.com/29292463/28425087-4b6fafca-6d3d-11e7-9e91-63a4e95e3a8b.png>

[central_programming]<https://user-images.githubusercontent.com/29292463/28425334-f600c50a-6d3d-11e7-870d-4d4ed6fc47a9.png>

**Comment by mcdoash** [comment]
What do you mean? I didn't change the grey box if that's what you're talking about.

**Comment by Amyffz** [comment]
Not the message board, I mean the messages section, leave them as is

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 20, 2017, at 11:55 AM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

What do you mean? I didn't change the grey box if that's what you're talking about.

**Comment by mcdoash** [comment]
Sorry but I still don't know what you mean. There isn't a messages section?

**Comment by Amyffz** [comment]
weekly annoucements i mean

**Comment by mcdoash** [comment]
OOHH yeah don't worry I didn't change that. So which of the two images do you like better/should I make any adjustments to them??

**Comment by mcdoash** [comment]
Here's what I have done tho: 

<img width="855" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28427988-dea23a1c-6d45-11e7-9000-23fb15a95317.png">

Also the word "Announcements" is really long and causing problems. I had to make the font really small on smaller widths because of it (this is roughly the size of a phone screen):

<img width="331" alt="central_programming_and_central_programming" src="https://user-images.githubusercontent.com/29292463/28428083-330ec796-6d46-11e7-92fa-1479833643ad.png">

**Comment by Amyffz** [comment]
can't see th photo you meant to send with "Here's what I have done tho: " and i prefer the one on top. Send me one where there's no shadow at all, let me compare

**Comment by mcdoash** [comment]
<img width="852" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28428368-39507c7a-6d47-11e7-896e-53e748016184.png">

I can change the padding or border to anything else you think would look better. 

Here's the photo that didn't send:

<img width="841" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28428421-5c9f03f4-6d47-11e7-8209-2760f2cd26f0.png">

You saw the second photo right? Should we change the wording or does it look fine? I also removed the rounded edge at that size???

**Comment by Amyffz** [comment]
PERFECT

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 20, 2017, at 12:32 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

[central_programming]<https://user-images.githubusercontent.com/29292463/28428368-39507c7a-6d47-11e7-896e-53e748016184.png>

I can change the padding or border to anything else you think would look better.

Here's the photo that didn't send:

[central_programming]<https://user-images.githubusercontent.com/29292463/28428421-5c9f03f4-6d47-11e7-8209-2760f2cd26f0.png>

You saw the second photo right? Should we change the wording or does it look fine? I also removed the rounded edge at that size???

**Comment by mcdoash** [comment]
✔️ ✔️ ✔️

**Comment by Amyffz** [comment]
can you experiment with ways to separate the 2 sections a bit? like perhaps adding a background, use a line or something, just try a couple of things and screenshot.

**Comment by mcdoash** [comment]
yep hold on

**Comment by mcdoash** [comment]
1)
<img width="1439" alt="central_programming_and_ __users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_stylesheet_css__culminating__ _brackets" src="https://user-images.githubusercontent.com/29292463/28429994-ceb27228-6d4c-11e7-82a9-397ff7734148.png">

**Comment by mcdoash** [comment]
2)

<img width="1439" alt="central_programming_and_ __users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_stylesheet_css__culminating__ _brackets" src="https://user-images.githubusercontent.com/29292463/28430191-9e23ff18-6d4d-11e7-8d78-e922a646b7c8.png">

**Comment by mcdoash** [comment]
3)

<img width="1438" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28430414-7749abe4-6d4e-11e7-8cee-24a542c0b7bd.png">

**Comment by Amyffz** [comment]
I like second, tag Fay and Angela and ask them


Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 20, 2017, at 1:10 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

  1.

[central_programming_and_ __users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_stylesheet_css__culminating__ _brackets]<https://user-images.githubusercontent.com/29292463/28429994-ceb27228-6d4c-11e7-82a9-397ff7734148.png>

**Comment by mcdoash** [comment]
@Fay-Z @AngelaZ0 Which do you like better? Also open to other suggestions.

**Comment by mcdoash** [comment]
When you view it a a small window/device it changes from "Weekly Announcements" to "Weekly News" so it fits better:

<img width="328" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28431314-f0904b04-6d51-11e7-8638-d90bc40b5452.png">

**Comment by AngelaZ0** [comment]
Fay and I also think the second one is the best, too.

**Comment by mcdoash** [comment]
Awesome!! I will add that in, then.

**Comment by mcdoash** [comment]
Alternately:

<img width="1438" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28474716-a04b7f76-6e17-11e7-85e3-1b23f63f677c.png">
Or some variation thereof.
I forgot about gradients.

**Comment by Amyffz** [comment]
I don't like the gradient

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 21, 2017, at 1:22 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Alternately:

[central_programming]<https://user-images.githubusercontent.com/29292463/28474716-a04b7f76-6e17-11e7-85e3-1b23f63f677c.png>

Or some variation thereof

**Comment by mcdoash** [comment]
That's alright, I'll remove it

**Comment by Amyffz** [comment]
Let's keep our website as flat as possible. Idk if that makes sense

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 21, 2017, at 1:24 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

That's alright, I'll remove it

**Comment by mcdoash** [comment]
I think so? We have a lot of box shadows, though

**Comment by Amyffz** [comment]
Well talk about it later/ soon

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 21, 2017, at 1:30 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

I think so? We have a lot of box shadows, though

**Comment by AngelaZ0** [comment]
Fay and I think the flat one is more simple and clear, we both like the original one
