### ISSUE TITLE
Resource page dropdown

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#10]
So since we're not putting the information directly on the website anymore do we still need the dropdown on the navigation bar? Here's a picture of what I'm referring to:

<img width="925" alt="resources_section_dropdown" src="https://user-images.githubusercontent.com/29292463/28332370-8f3f2950-6bc2-11e7-8794-5d403b15fca6.png">

**Comment by AngelaZ0** [comment]
I think we could leave the information on the website if it's still on there and keep the dropdown, while we are also putting information on google docs.

**Comment by mcdoash** [comment]
Wait I'm confused. I thought we were only posting the information on the google docs and then linking to it? We can of course put them on the website too though, that's not a problem, whichever you guys prefer. We should probably start working on the resource section soon.

**Comment by Amyffz** [comment]
i think that in the website we can include actual information, like a short how to. but then links to a doc that has examples and homework help, practices etc
