### ISSUE TITLE
Website Content

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#12]
So now that the design is more or less complete, we should start filling out the text on the page. If you'd like you can make another branch off of the main-page-redesign branch and edit the html directly. Let me know if you have any problems doing so.

## Main Page
- [x] Welcome section
- [x] Weekly announcements
- [x] Club Info section
     - [x] About the CPC
     - [x] Why Learn Code
- [ ] Team section
     - [x] Amy
     - [x] Angela
     - [x] Ashley
     - [x] Fay
     - [ ] Ms. Ward
     - [x] You
## Weekly Problems
- [x] Purpose
- [x] First week's problem

## Contests
- [x] Central 1
- [x] Central 2
- [x] CCC
- [x] Central 3
- [x] ECOO

**Comment by mcdoash** [comment]
@Fay-Z @Amyffz @AngelaZ0 Should I put some filler content in before I merge with the master branch/publish online or should I leave the gibberish?

**Comment by Amyffz** [comment]
merge it for now so at least we can see the final design

**Comment by mcdoash** [comment]
Alright, just cleaning it up a little and adding comments for accessibility.

**Comment by mcdoash** [comment]
Website is up!! @Amyffz @Fay-Z @AngelaZ0 
Check it out [here](https://centralprogramming.github.io/).
Please let me know if you see any bugs by creating a new issue. It would also be great if you view it on any devices you have (both portrait and landscape orientations if applicable) to see if it looks alright.

**Comment by Amyffz** [comment]
OMG it's so good
I have 2 awkward situations.
1.the title font
2. About ccc is too wide

**Comment by mcdoash** [comment]
@Amyffz could you please check out the checklist and make your comments on #7 "General Respomsiveness"? Please tell me the device, orientation or window size, and your problems there. I'll check it out in the morning.

**Comment by mcdoash** [comment]
Just letting you guys know that the site [dillinger](http://dillinger.io/) is great for writing text in markup (the [same type](https://help.github.com/articles/basic-writing-and-formatting-syntax/) that GitHub uses) and then converts it to html, which I can then insert into the site for you. Otherwise you could just show me how you want it stylized.

**Comment by mcdoash** [comment]
How does this sound for a description of weekly problems?

> Programming problems are a great way to prepare for contests, practice your coding skills, and exercise problem solving. With that in mind, a new problem from <a href="https://dmoj.ca/">DMOJ</a> will be posted here every *Sunday(?)*. By participating in and solving these problems, you will earn points that go towards monthly and year-end prizes. You don't have to make a commitment to participate every week (because who had time for that at Central?); simply try a problem at home when you have time, or come in during one of our meetings and solve it with the help of your peers.

Is it too formal or too long??? 

Also, [here's the link](https://docs.google.com/a/gotvdsb.ca/document/d/1IOCOfLpvPor-rREKBnKyUCfLL1fPZ3mHGc-TbokWL9k/edit?usp=sharing) to the google doc from today If you'd like to reference the points we added before you write any content.

@Amyffz @Fay-Z @AngelaZ0

**Comment by mcdoash** [comment]
I've added some content and images. Feel free to change any of it.

**Comment by Fay-Z** [comment]
I think this Description has many good contents, a little bit formal is
good( shows our profession:) For the first part of the paragraph, or in the
introduction of our club, I think you can add something relate the
potential of programming, how programming going to benefit you? I guess,
like saying programming is the foundation of AI. Not sure if that help, you
can add if you want.

Another thing: should we talk about the kind of prize we want to give them?

**Comment by mcdoash** [comment]
@Fay-Z Hmm alright, I'll try adding that in the about section. 
I'm not sure if we've really decided on the prizes yet. Some ideas from the google doc were "Monthly Food, gift card, cool gadgets".

**Comment by Fay-Z** [comment]
Yeah,those ideas are good. I was also thinking that we can try to make some t-shirts or badges that has programming club printed on them. And give them away as prizes. Although I am not sure how we can do this, we can ask Ms.Ward probably. And there is no rush in doing this (maybe too much work), we can deal with this later if decided to do so.

**Comment by mcdoash** [comment]
Yeah, we had plans to make merch (probably shirts or sweaters) anyways, so that could work! The same company that made the art sweaters might be a good choice.  @Fay-Z

**Comment by Fay-Z** [comment]
That’s awesome. How much will each shirt or sweater costs?

**Comment by mcdoash** [comment]
Hmm I'm not sure. For the art ones, I think shirts were about $15 and sweaters were $25-$30. @Fay-Z

**Comment by Fay-Z** [comment]
Alright, that’s not a bad prize. We can plan it after we meet.

**Comment by mcdoash** [comment]
Could you guys give me ideas on why programming is important to learn? @Amyffz @Fay-Z @AngelaZ0

**Comment by mcdoash** [comment]
Also could everyone write a blurb about themselves? I think we decided to include why we enjoy programming and what we hope to do in the future?? I'm not sure what else. @Amyffz @Fay-Z @AngelaZ0

**Comment by mcdoash** [comment]
It should be in third person and maybe 50 words long max?

**Comment by mcdoash** [comment]
I'm just going to mark this as closed, cause who knows when we'll be able to finish it.
