### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Amyffz** [CentralProgramming/CentralProgramming.github.io#13]
I have started the logo design process, there should be an update by 21st. I will keep everyone updated here. Please post suggestions and inspirations here as well.

**Comment by mcdoash** [comment]
Are you making it yourself or paying someone to?

**Comment by Amyffz** [comment]
I am designing it and then paying someone to make it digital

**Comment by mcdoash** [comment]
You don't have to pay anyone! If it's just making it digital I have a graphics tablet we can use. I don't want you to have to spend so much money on this.

**Comment by Amyffz** [comment]
It's okay, I'm giving Ridvan business

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 19, 2017, at 6:24 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

You don't have to pay anyone! If it's just making it digital I have a graphics tablet we can use.

**Comment by mcdoash** [comment]
lol okay

**Comment by Amyffz** [comment]
Here are three random ones created with a logo generator, any you guys like? I like the second one but perhaps with a thicker/bolder font?

[CENTRAL_CODING_CLUB.pdf](https://github.com/CentralProgramming/CentralProgramming.github.io/files/1162588/CENTRAL_CODING_CLUB.pdf)

**Comment by Amyffz** [comment]
![download](https://user-images.githubusercontent.com/29757934/28422234-6c4ff0e0-6d35-11e7-9002-e3e16d63e9e7.jpeg)
![logo-02](https://user-images.githubusercontent.com/29757934/28422233-6c4f60da-6d35-11e7-9cd8-23f9fa58c7ed.png)
![logo](https://user-images.githubusercontent.com/29757934/28422235-6c53b4aa-6d35-11e7-9169-fb8bb1918aa6.png)
![ccclogo](https://user-images.githubusercontent.com/29757934/28422239-709c63e0-6d35-11e7-868d-3b7d8be4c595.png)
Here are sme i found online for inspiration

**Comment by mcdoash** [comment]
So we are definitely "Central Coding Club"?? If so we'd need to officially change our name. I really like the ones on the pdf, especially the first and last one. But for the first one, since we work mainly in java, wouldn't it make more sense to use curly braces instead of angle brackets? I'd like the second one better if the diamond was behind the text maybe? Not sure it that would work.

**Comment by Amyffz** [comment]
im paying with both idea, really just which one would have a better logo at this point

**Comment by mcdoash** [comment]
I'm thinking the last one?? But they're all good.

**Comment by mcdoash** [comment]
Also uh, if we change the name to coding club we're going to have to change the github name. Are we 100% changing it??

**Comment by Amyffz** [comment]
Not sure but I'm highly leaning ccc

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 20, 2017, at 1:33 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Also uh, if we change the name to coding club we're going to have to change the github name. Are we 100% changing it??

**Comment by mcdoash** [comment]
If we're Central Programming then something like this?

![logo](https://user-images.githubusercontent.com/29292463/28482629-3977890a-6e37-11e7-87ce-fbf8893a0899.png)

**Comment by Amyffz** [comment]
Em

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 21, 2017, at 5:09 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

If we're Central Programming then something like this?

[logo]<https://user-images.githubusercontent.com/29292463/28482629-3977890a-6e37-11e7-87ce-fbf8893a0899.png>

**Comment by mcdoash** [comment]
em?

**Comment by AngelaZ0** [comment]
We prefer the first one, it's cool and very unique !

**Comment by Amyffz** [comment]
kay guys ridvan is officially on him, lets see where his creativity takes him

**Comment by Amyffz** [comment]
![received_842435209246589](https://user-images.githubusercontent.com/29757934/29754820-1e70f916-8b5b-11e7-8d93-f448398952fe.jpeg)

**Comment by Amyffz** [comment]
We can change the font if anything

**Comment by mcdoash** [comment]
Hmm I like it! What if we put the text to the right? Also are we central programming or central programming club officially? Central programming would probably fit better on the website but club might make more sense.

**Comment by mcdoash** [comment]
We're also going to need a transparent version of it

**Comment by Amyffz** [comment]
We're Central programming club, but the logo really only need Central programming. It's like deca. It's deca club but shirts only say deca.

Sent from BlueMail<http://www.bluemail.me/r?b=10215>
On Aug 27, 2017, at 8:35 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm I like it! What if we put the text to the right? Also are we central programming or central programming club officially? Central programming would probably fit better on the website but club might make more sense.

**Comment by mcdoash** [comment]
Makes sense. What should we put on the website header though?

**Comment by mcdoash** [comment]
Hey, @Amyffz, could you ask Lily for a transparent (probably png) version? Also are we moving the text to the right or using the text that's already on the website for the header? Either way, a version without the text would be great too.

**Comment by Amyffz** [comment]
maybe you can put central programming or cpc. i'll make the versions you wish for rn

**Comment by mcdoash** [comment]
You mean for the header? @Amyffz I'll do up some options once I have the transparent logo.

**Comment by mcdoash** [comment]
Something roughly like this, with different colours maybe? Also a different image (#33)? @Amyffz 

<img width="1439" alt="central_programming_and_ __users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_css_main_css__culminating__ _brackets" src="https://user-images.githubusercontent.com/29292463/30004155-ed612840-9097-11e7-96c6-0b86cf17f233.png">

**Comment by mcdoash** [comment]
It's live on the homepage now @Amyffz

**Comment by mcdoash** [comment]
@Amyffz Has Lily sent you the logo yet? The one on the website now is pretty low quality.

**Comment by mcdoash** [comment]
Hmm never mind the bad quality part, seems I just had the wrong image.

**Comment by mcdoash** [comment]
Guess we can close this now.

**Comment by mcdoash** [comment]
Putting these here for easy access:

![header-strip](https://user-images.githubusercontent.com/29292463/31310818-b0f3bcde-ab6c-11e7-8f8e-464b6cb29f61.png)
![21362300_845863512237092_1949798360_o](https://user-images.githubusercontent.com/29292463/31310819-b3595308-ab6c-11e7-9c9a-68f7d42b60b6.jpg)
![cpc-logo-transparent](https://user-images.githubusercontent.com/29292463/31311247-252a35e8-ab76-11e7-949e-e191b3e7810b.png)
