### ISSUE TITLE
Official club name

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#16]
Are we "Central Programming Club" or "Central Coding Club"? Vote now.

**Comment by mcdoash** [comment]
I like "Programming Club" personally, mostly because "Central Coding Club" is confusing with the CCC computer contest

**Comment by mcdoash** [comment]
@Fay-Z @Amyffz @AngelaZ0

**Comment by AngelaZ0** [comment]
Central programming club,

**Comment by mcdoash** [comment]
@Fay-Z @Amyffz

**Comment by Amyffz** [comment]
i dont care really, i am asking peoples opinions

**Comment by mcdoash** [comment]
Hey so do we have any other options or are we still just debate between Central Programming Club (CPC) or Central Coding Club (CCC)? I guess we could be London Central Coding/Coders (LCC) or something but that might not sound as good???

**Comment by Amyffz** [comment]
lets do cpc

**Comment by Fay-Z** [comment]
Central Programming club
