### ISSUE TITLE
Weekly Problems Page Layout

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#18]
So I was thinking maybe the basic layout could be something like this?

<img width="460" alt="weekly_problems_layout" src="https://user-images.githubusercontent.com/29292463/28647744-02a92dda-7237-11e7-9133-6d40381c0e32.png">

I was also wondering: is the leaderboard going to be for all DMOJ problems or just the results of the weekly problems?

@Fay-Z @Amyffz @AngelaZ0

**Comment by mcdoash** [comment]
I completely forgot a place for last week's winner. Maybe between the About and This Week's Problem?

**Comment by AngelaZ0** [comment]
problems and results
btw about and this week's problem is fine

**Comment by mcdoash** [comment]
I'm going to see if I can just directly add the table from DMOJ in there, but I'm not sure if I can without using some kind of server.

**Comment by mcdoash** [comment]
So I don't think I can put the leaderboard from DMOJ on the website, since they don't allow embedding. 

A few other options:
- I create our own table and update it every so often and link to the DMOJ rankings. This means that the website ranking will be out of date most of the time.
- We make our own set of rankings (ex. just weekly problems, some other criteria) that is completely separate from the DMOJ rankings. This will allow for the website rankings to always be up to date, but may cause confusion?
- Just link to the DMOJ without having a leaderboard on the website

Thoughts/other alternatives? @AngelaZ0 @Fay-Z @Amyffz

**Comment by mcdoash** [comment]
Maybe they can get extra points for top scores in weekly problems?

**Comment by mcdoash** [comment]
Maybe they get extra points for:
- top scores in weekly problems
- showing up to meetings
- participating in contests + their ranking

**Comment by mcdoash** [comment]
![image](https://user-images.githubusercontent.com/29292463/28759210-5fe75524-7568-11e7-87c1-da477eeb1d80.png)

**Comment by Amyffz** [comment]
ugh, so good

**Comment by AngelaZ0** [comment]
Everything looks great!
