### ISSUE TITLE
Domain & hosting

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#19]
So I've been spending the last few days learning PHP, which is a language that lets you add dynamic content to webpages. I'd finally finished a contact form and some other stuff, but when I went to upload it I realized that GitHub Pages doesn't support PHP. So either we ditch the PHP, or we will probably have to pay for web hosting elsewhere.

What I was planning on using PHP for:
- Add in content like the header, footer, etc. that doesn't change between pages
- A contact form that automatically sends emails
- Auto update the leaderboard
- Anything else that needs dynamic content

idk if these features will be worth paying like $7 extra per month. There might be somewhere  else out there that's a lot cheeper? I haven't looked into web hosting that much.

**Comment by mcdoash** [comment]
It will also make the Past Problems section *so* much easier to maintain.

**Comment by Amyffz** [comment]
if it really helps, i dont think 7 dollars a month is too much. Sorry can't help you much with this as we dont exactly understand how much easier it makes things. it'll just be up to you! Do whatever you want! Speaking of that, i think we should get our domain now.

**Comment by mcdoash** [comment]
Sounds good!! I guess we need to decide on a name first though?

**Comment by mcdoash** [comment]
https://www.000webhost.com/

**Comment by mcdoash** [comment]
Some possible hosting sites:
[Bluehost](https://www.bluehost.com/hosting-features) &mdash; $7.99/mo
[Hostgator](https://www.hostgator.com/shared-compare) &mdash; price varries
[Canadian Web Hosting](https://www.canadianwebhosting.com/hosting/linux_hosting) &mdash; $3.95-$4.95/mo
[GoDaddy](https://ca.godaddy.com/hosting/web-hosting) &mdash; $7.99/mo
