### ISSUE TITLE
Colours and Fonts

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#2]
# Colours
Any feedback on the colours so far? The background of the "Intro" Section is especially off I think. Maybe it should be white? The title font/colour will definitely be changed once we have an actual logo.

# Fonts
We need to select 2-3 fonts for the titles and paragraphs. The paragraph text should be a serif of some sort, with the others possibly being sans-serif?? It would be helpful if the fonts were selected from [Google Fonts](https://fonts.google.com/) to easily add it to the website.

**Comment by Amyffz** [comment]
i really like :VT323 — Regular
idk where we would implement it, idk, maybe something small like our names

**Comment by Amyffz** [comment]
I really really like Monoton  as well, can we use it for like a title

**Comment by Amyffz** [comment]
after changing some of it, can you send me a screenshot so i can decide on the font for the headers (like for resources, contests etc those stuff)

**Comment by mcdoash** [comment]
These fonts right?

<img width="374" alt="google_fonts" src="https://user-images.githubusercontent.com/29292463/28383530-7318ed56-6c8f-11e7-8793-57a96a199287.png">
<img width="369" alt="google_fonts" src="https://user-images.githubusercontent.com/29292463/28383552-83738940-6c8f-11e7-85d3-5225f140101a.png">

I'll put them in then add photos.

**Comment by mcdoash** [comment]
It would need a bit of adjusting but here:

<img width="1439" alt="central_programming_and__users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_stylesheet_css__culminating__ _brackets" src="https://user-images.githubusercontent.com/29292463/28384604-4e012d4a-6c93-11e7-9d2f-8975ff919765.png">
<img width="1439" alt="central_programming_and_ __users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_stylesheet_css__culminating__ _brackets" src="https://user-images.githubusercontent.com/29292463/28384733-b98429a0-6c93-11e7-8c79-8be7a710ab57.png">

**Comment by Amyffz** [comment]
i think only use monoton for the big title, or else its a bit too much

**Comment by mcdoash** [comment]
I really like the VT323 font. What should we use for smaller subheadings then? Also are we just leaving the regular paragraph font as it is?

**Comment by Amyffz** [comment]
i dont really like vt323 on the black bar either... idk a bit too much, those would be like accent fonts

**Comment by mcdoash** [comment]
Hmm okay. I can change it to different fonts if you'd like.

**Comment by Amyffz** [comment]
Let's meet again next month to finalize those stuff, it's hard to do here

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 20, 2017, at 11:33 AM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm okay. I can change it to different fonts if you'd like.

**Comment by mcdoash** [comment]
Agreed. Why next month though?

**Comment by Amyffz** [comment]
I legit have no free time this month, and in August there's only 1 week I'm free


Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 20, 2017, at 11:54 AM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Agreed. Why next month though?

**Comment by mcdoash** [comment]
Ah alright. That's fine then! It's alright if you don't have time to work on the website till then.

**Comment by mcdoash** [comment]
@Fay-Z @AngelaZ0 What do you think of these fonts? 

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28482468-7b6c58b4-6e36-11e7-8d7d-fdf3245da26d.png">
<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28482481-8a959b98-6e36-11e7-9c6f-99d74877acfb.png">


Also, which do you like better,
Flat: 

<img width="1147" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28482526-c3c8d11e-6e36-11e7-8465-4f6e2804b52a.png">


Or shadow:

<img width="1146" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28482501-aca16c62-6e36-11e7-8df9-3084b682690e.png">

**Comment by AngelaZ0** [comment]
I like the big title in original font than monotone font, maybe put Welcome to CCC in monoton font? and connecting central coder in vt323? And I like both the shadow and flat, but the shadow one is better

**Comment by mcdoash** [comment]
If we put the VT323 for the "Connecting Central Coders" then we should use it somewhere else too. I don't think we should use so many fonts; it will make it too complicated. I like the shaded better as well.

**Comment by AngelaZ0** [comment]
I agreed, too much font is not good.

**Comment by Amyffz** [comment]
I think monton for the big tittle is good. I really don't think three ish font is too much.

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 21, 2017, at 10:44 PM, AngelaZ0 <notifications@github.com<mailto:notifications@github.com>> wrote:
I agreed, too much font is not good.

**Comment by Amyffz** [comment]
If anything, I think we should cut down on the vt font, because like it's a bit distracting. Other than the main title the other fonts should be a bit more simple.

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 21, 2017, at 5:05 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

@Fay-Z<https://github.com/fay-z> @AngelaZ0<https://github.com/angelaz0> What do you think of these fonts?

[central_programming]<https://user-images.githubusercontent.com/29292463/28482468-7b6c58b4-6e36-11e7-8d7d-fdf3245da26d.png>

[central_programming]<https://user-images.githubusercontent.com/29292463/28482481-8a959b98-6e36-11e7-9c6f-99d74877acfb.png>

Also, which do you like better,
Flat:

[central_programming]<https://user-images.githubusercontent.com/29292463/28482526-c3c8d11e-6e36-11e7-8465-4f6e2804b52a.png>

Or shadow:

[central_programming]<https://user-images.githubusercontent.com/29292463/28482501-aca16c62-6e36-11e7-8df9-3084b682690e.png>

**Comment by mcdoash** [comment]
I agree. Personally I really like all the fonts that are in there right now. Except maybe the title font, but I don't really mind it.

**Comment by mcdoash** [comment]
Hey, are we solid on all the fonts/colours that are in there now? @Amyffz @AngelaZ0 @Fay-Z. I feel like this issue can probably be closed.

**Comment by Amyffz** [comment]
close it

**Comment by mcdoash** [comment]
Bringing this back because the header font looks disgusting on safari:

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/30084870-297f881e-9262-11e7-8a1d-0fa35a1a1c4d.png">

**Comment by mcdoash** [comment]
Since no one suggested a font I just chose one. Tell me if you don't like it but otherwise this is closed.
