### ISSUE TITLE
Contests page layout

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#21]
Idea: 
<img width="720" alt="marvel_-_central_programming_website" src="https://user-images.githubusercontent.com/29292463/28800127-670d226e-7619-11e7-820e-7e428c9b3ca7.png">

When you click on one of the cards they "flip" over and show information??? Or just put the info right on the card.

**Comment by mcdoash** [comment]
Card flip looks like this:

![flipcard](https://user-images.githubusercontent.com/29292463/28843804-79950390-76d0-11e7-9689-18a25a58e934.gif)

**Comment by mcdoash** [comment]
# Current contests page with some cards flipped:

![image](https://user-images.githubusercontent.com/29292463/28905024-afa2a516-77dc-11e7-9c9e-269e23cf0a76.png)


# Bottom part without past contests:

![download](https://user-images.githubusercontent.com/29292463/28905169-542b32c4-77dd-11e7-97a8-17cb62d1765f.png)


Thoughts? @Fay-Z @Amyffz @AngelaZ0

**Comment by Amyffz** [comment]
LIKE ITS SOOOO AMAZING, I LOVE THE FLIPPY THINGY. THE SAMPLE PROBLEM IS SUCH A SMART IDEA!

**Comment by mcdoash** [comment]
Thanks!! I'd like to add more animations around the site to make it look better, but idk where. I'm excited that it's all finally coming together :)

**Comment by Fay-Z** [comment]
Thanks, Ashley.
