### ISSUE TITLE
Other Features

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#22]
As I'm nearing the last page or so of the website, I was just wondering if there was any other pages/features you guys would like me to put in. I know we discussed a calendar at some point? Is that something we still want? 

Also what about contact forms? I've made a mock-up of one that actually works, but needs PHP (#19). Here's what it looks like by the way:

![download](https://user-images.githubusercontent.com/29292463/28905587-98821206-77df-11e7-9dbf-1111b047c78f.png)

Anyways, I'd appreciate it if you let me know of any ideas you have, and I'll see if I can put it in. The last two pages have gone a lot faster than I expected, so I should have time. Then again, we still have to put in all the content.

 @Fay-Z @Amyffz @AngelaZ0

**Comment by Amyffz** [comment]
i really like the get in touch thing going  on, but dont we already have the contact information beneath the team member thing? I may be just remebering things incorrectly though. a calendar would be nice, but i think a list of events in chronological order would be just as sufficient

**Comment by mcdoash** [comment]
Depends on what you prefer. If you click the contact on the team section it opens your email application so you have to send it yourself. The form is just a way to send the message for them I guess? If we do use the form it could link from the contact buttons. Idk if we need a form really.
The list would be faster. I'll see what I can do.

**Comment by mcdoash** [comment]
So we can just embed a google calendar which is much easier to add events to. Plus that way people can save the events to their own calendar if they'd like. I'd start the calendar now but my tvdsb account has been disabled? Is that just me or did the board disable all of them over the summer?

**Comment by Amyffz** [comment]
sure! dont let that take too much of the page

**Comment by mcdoash** [comment]
I was thinking of putting it on a separate page maybe since it would be pretty big?

**Comment by mcdoash** [comment]
@Amyffz I made it a separate page for now but can definitely change it.

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/29744389-f9c274b2-8a71-11e7-8d39-74089bdb3467.png">
<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/29744392-088d8d56-8a72-11e7-90f2-15e17c3f4759.png">

**Comment by mcdoash** [comment]
I guess this can be closed? We talked briefly about making a members area but that'll be far in the future. Discussion of the calendar section has been moved to #28.
