### ISSUE TITLE
Resources Page Layout

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#23]
Sorry for posting so much lately. I hope it isn't getting too annoying. Just tell me if it is, or if you're even interested in me making these.

Anyways, here's my idea for the resources page:
<img width="718" alt="marvel_-_central_programming_website" src="https://user-images.githubusercontent.com/29292463/28905708-729bdefe-77e0-11e7-8443-cc81c4af8059.png">

And when it's on mobile maybe something like this???

<img width="317" alt="marvel_-_central_programming_website" src="https://user-images.githubusercontent.com/29292463/28905697-5e2cafde-77e0-11e7-9c11-c502d6bff095.png">

@Fay-Z @Amyffz @AngelaZ0

**Comment by Amyffz** [comment]
so yellow=main category, gray = sub. are we dividing it between grades?

**Comment by mcdoash** [comment]
Hmmm I hadn't thought of that. I'm not even sure what we're putting in the resource section. The categories there were just some of my ideas.

**Comment by mcdoash** [comment]
The navigation on the left looks kinda bulky and weird?? Not sure what other design would work

![image](https://user-images.githubusercontent.com/29292463/29004922-f2fa4a12-7a9d-11e7-9f5a-e9af05674f5d.png)

**Comment by Amyffz** [comment]
try making them flatter?

**Comment by mcdoash** [comment]
What about something like this where when you click on a section it expands to show the categories?

<img width="309" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/29051924-2b2c993c-7bb4-11e7-9a1a-06743705b4d9.png">

**Comment by Fay-Z** [comment]
Great Idea, I would prefer aligning the text to the left rather than the centre. 
tab each sub 
and the colour of the text can be the same. or you can bold the main, and normal for the sub categories.

**Comment by mcdoash** [comment]
@Fay-Z more like this?

<img width="311" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/29087555-55c87586-7c44-11e7-8261-188e41311387.png">

**Comment by Fay-Z** [comment]
Yeah, 👍

**Comment by Amyffz** [comment]
ye

**Comment by mcdoash** [comment]
Should the content nav be sticky (i.e. moves with the page so that it's always visible at the side) but scrolls,

<img width="1439" alt="central_programming_and__users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_css_resourcespage_css__culminating__ _brackets_and_centralprogramming_github_io_ _-bash_ _80x18" src="https://user-images.githubusercontent.com/29292463/29144429-f8e4afea-7d26-11e7-8296-0e416b72010a.png">

or stay fixed (i.e. stay at the top of the content box and you will have to scroll up to access it) and be able to expand fully on the page:

<img width="1439" alt="central_programming_and_resources_page_layout" src="https://user-images.githubusercontent.com/29292463/29144538-5281d4c4-7d27-11e7-9b2f-197056566847.png">

Does that make sense??? Like if we want the nav to be sticky the navigation box itself will have to scroll up and down to show the rest of the links. I'm not sure which is better. @AngelaZ0  @Amyffz @Fay-Z

**Comment by mcdoash** [comment]
Otherwise this page is done?? Besides deciding on/writing the actual content of course. Unless there's anything you think we need? I could add a place for people to suggest/submit new content?

**Comment by Amyffz** [comment]
Merge it?

Sent from BlueMail<http://www.bluemail.me/r?b=10215>
On Aug 9, 2017, at 5:26 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Otherwise this page is done?? Besides deciding on/writing the actual content of course. Unless there's anything you think we need? I could add a place for people to suggest/submit new content?

**Comment by Fay-Z** [comment]
This page is good. I think it is better to let it be sticky.

**Comment by mcdoash** [comment]
@Amyffz Just finishing up the navigation for smaller devices which is a bit harder than I thought. 

<img width="402" alt="resources_page_layout_ _issue__23" src="https://user-images.githubusercontent.com/29292463/29194933-e8c61238-7df9-11e7-9a19-5f11dcab8e60.png">

I'm thinking of making it so that when you click on the category or section the rest of the links expand out. Still working on that tho.

We could merge the contests and problems pages now if you'd like. They've been done for a while

**Comment by mcdoash** [comment]
So I changed it again:

<img width="366" alt="central_programming_and_central_programming_and__users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_css_resourcespage_css__culminating__ _brackets_and_central_programming" src="https://user-images.githubusercontent.com/29292463/29244272-ed22e7dc-7f81-11e7-9d2b-805b424d27e4.png">

The other one was too complicated/hard to do but still possible if you guys like it better I guess. The new one is pretty much the same as the basic nav except the links expand to the right instead of underneath. I feel like it looks too empty before the sections are expanded though so I might put something there initially.

**Comment by Amyffz** [comment]
its fine either way, good job ashley!

**Comment by mcdoash** [comment]
Thanks!!! The entire site is almost done now 😄

**Comment by mcdoash** [comment]
Are we going to be linking to outside resources as well? If so, it might be better to have the main resources page show all that then link to our own stuff. Or we could put it on the bottom of the page?

**Comment by Fay-Z** [comment]
I think it's fine to just put them at the bottom of the page
