### ISSUE TITLE
Announcements/calendar section

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#28]
I know we already talked about this but I had some other ideas. Regarding the weekly announcement section, would it be better to just change it to "announcements"? We will probably only have things to add there for the big meetings once a month.

What do you think of this for the first meeting (I just stuck a random date in there for now):

![image](https://user-images.githubusercontent.com/29292463/29846979-54d3b84e-8ce7-11e7-8e38-aaa5329373eb.png)

As for the calendar, the events thing looks really ugly, and the regular calendar is pretty big. I'd suggest putting the calendar on a separate page maybe, but all three options would be fine. Otherwise we could add our own events?

On a kind of related note, what do you guys think about changing the highlight showing which page you're on to purple?

<img width="1437" alt="central_programming_and__users_ashley_documents_school_programmingclub_website_centralprogramming_github_io_css_main_css__culminating__ _brackets_and_new_issue_ _centralprogramming_centralprogramming_github_io" src="https://user-images.githubusercontent.com/29292463/29847025-916128d2-8ce7-11e7-91b5-dce43b09f71d.png">

@Fay-Z @Amyffz @AngelaZ0

**Comment by Fay-Z** [comment]
Sure, it will be cool to change it to purple. 
Yeah, probably announcement will be enough instead of weekly announcement
You are right about the calendar, it effects the overall style the website, I would also prefer to move it to a different page.

**Comment by mcdoash** [comment]
@Fay-Z I'll put it in now 😄

**Comment by mcdoash** [comment]
Thoughts?

![image](https://user-images.githubusercontent.com/29292463/29953050-2896ca2c-8e9b-11e7-9aef-3b0847687f24.png)

**Comment by mcdoash** [comment]
I'm adding a back button now. Maybe. We'll see how it goes.

**Comment by mcdoash** [comment]
Added a "back" link &mdash; e0af6c3

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/29996824-c36614b6-8fd3-11e7-9634-cbb3ea7434bd.png">

**Comment by mcdoash** [comment]
Since no one has commented on this I'm just going to assume that everyone's fine with it and close the issue ¯\_(ツ)_/¯
