### ISSUE TITLE
Footer Content and Design

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#3]
The wix site still has the default footer, so I'm not sure what to put in it or if it's the right design. Whatever content we're going to put in it should appear on all pages. 
Here's a picture of the current footer (the yellow and grey stripes):

<img width="1439" alt="footer" src="https://user-images.githubusercontent.com/29292463/28332500-12cc7174-6bc3-11e7-9f7b-b52dc47c3d5c.png">

**Comment by Amyffz** [comment]
i think its good, theres definitely room to play with though

**Comment by Fay-Z** [comment]
The footer is fine. After we have too much stuff in the website, we can add headings like about, help, etc, later.  I like the github's footer design, we can also put our logo in the middle
<img width="971" alt="screen shot 2017-08-08 at 1 34 19 pm" src="https://user-images.githubusercontent.com/29312800/29085921-cc8b982a-7c3e-11e7-81fa-21476db1ac0f.png">

**Comment by mcdoash** [comment]
Here are some basic footer ideas. The content will definitely change, I'm just focusing on the design right now.

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/29290409-f9f654a2-810d-11e7-9485-43a4afbd9dea.png">
<img width="1434" alt="central_programming_and_footer_content_and_design_ _issue__3_ _centralprogramming_centralprogramming_github_io" src="https://user-images.githubusercontent.com/29292463/29296440-52a3ec12-8128-11e7-8acb-1f7a5f2b22ad.png">

**Comment by mcdoash** [comment]
Oh I completely forgot about our logo. Hmm...

**Comment by Fay-Z** [comment]
Looks amazing 😉.

**Comment by mcdoash** [comment]
@Fay-Z thank you!! Which do you like better? The first is more like GitHub's design but the second has more information.

**Comment by Fay-Z** [comment]
I would prefer the first one, it looks simple and clear.

**Comment by mcdoash** [comment]
I'll put the other footer design on the problems page so everyone can check them out for themselves

**Comment by mcdoash** [comment]
Whoops I forgot to make the alt nav responsive. Looks fine on desktop though

**Comment by mcdoash** [comment]
@Amyffz what do you think about the footer options?

**Comment by Amyffz** [comment]
i agree with fay, i like the first one

**Comment by mcdoash** [comment]
@Amyffz Alright then, I'll change all the footers.
