### ISSUE TITLE
Calendar page tag triangle thing is sometimes purple on Safari (?????) (AKA don't let me code this website)

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#32]
My best guess is it has something to do with the fact that it's a link.

**Comment by mcdoash** [comment]
I officially don't know what's going on anymore.

**Comment by mcdoash** [comment]
Never mind.

**Comment by Amyffz** [comment]
lol kay

**Comment by mcdoash** [comment]
Today has been interesting.

<img width="1159" alt="what-have-i-done" src="https://user-images.githubusercontent.com/29292463/29999757-6f4b5af4-9022-11e7-872e-b04a243b63bc.png">

Lol I definitely know what I'm doing.

**Comment by mcdoash** [comment]
![image](https://user-images.githubusercontent.com/29292463/29999799-6ad0a9d8-9023-11e7-8efb-1f01b4f5655b.png)

I changed one thing.
