### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by Amyffz** [CentralProgramming/CentralProgramming.github.io#33]
[PcENTRAL programming Club.pdf](https://github.com/CentralProgramming/CentralProgramming.github.io/files/1272664/PcENTRAL.programming.Club.pdf)

**Comment by Amyffz** [comment]
more changes could be made!

**Comment by mcdoash** [comment]
IT'S AMAZING!!! Just a few things:
- I feel like the name of our club should be bigger?
- The "Let's get ready to master the future" is *really* hard to see
- Pretty sure it's room 117??
- That won't be our permanent url
- The qr code is great! It will probably have to be changed when we get our domain, though
- I LOVE the bottom part!!
- Maybe get rid of the grey line separating the sections?

Overall it looks really good!!! Great job! 

Also how about Thursday the 14th for our first meeting? It's on the second week. Monday might be too early, Tuesday-Wednesday is a music field trip, and Friday is an assembly.

**Comment by mcdoash** [comment]
Ughh it's so good!!!

**Comment by mcdoash** [comment]
Hmm maybe also up the opacity on the logo? At least on the C and the P? I kind of like the transparency on the background, though.

**Comment by mcdoash** [comment]
What do you think about using the bottom half of the poster as the header image?

**Comment by Amyffz** [comment]
<img width="342" alt="screen shot 2017-09-03 at 9 57 08 pm" src="https://user-images.githubusercontent.com/29757934/30009081-7678c3bc-90f3-11e7-8cc1-39be521f9168.png">
<img width="342" alt="screen shot 2017-09-03 at 10 00 28 pm" src="https://user-images.githubusercontent.com/29757934/30009083-7c493eb6-90f3-11e7-90e9-5a58294a1133.png">


<img width="342" alt="screen shot 2017-09-03 at 9 56 23 pm" src="https://user-images.githubusercontent.com/29757934/30009079-7253aac2-90f3-11e7-97f2-908df4000ef6.png">
<img width="398" alt="screen shot 2017-09-03 at 9 59 28 pm" src="https://user-images.githubusercontent.com/29757934/30009075-6cea6f6c-90f3-11e7-9ef7-2df5af3cc12a.png">

**Comment by Amyffz** [comment]
couple of options here,
i like the second one
and yes i will fix the transparancy of the logo once lily sends me the tranparent options

**Comment by mcdoash** [comment]
Oh, they're all so good!!!! I love the second one as well.

**Comment by Amyffz** [comment]
[PcENTRAL programming Club (1).pdf](https://github.com/CentralProgramming/CentralProgramming.github.io/files/1279228/PcENTRAL.programming.Club.1.pdf)
final-ish version

**Comment by mcdoash** [comment]
Wow, nice!!! Thanks for making the poster, you did an amazing job!
