### ISSUE TITLE
Team Section Layout

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#4]
The way it's setup makes it spread out and very long. Would it be better to set it up in a 2x2 table instead?

**Comment by mcdoash** [comment]
I created one alternate idea in the alt-team-layout branch (commit 8db231975d7f072f9ebb8bc8611bc26a5256b3e2). It adds a more stylized look that seems a bit more professional. I'd appreciate it if you gave me feedback or alternate ideas. @Fay-Z @Amyffz @AngelaZ0

**Comment by mcdoash** [comment]
I'm adding photos so it's easier for everyone to see. Here's the old team layout:

<img width="1439" alt="old_team_layout" src="https://user-images.githubusercontent.com/29292463/28333287-7203d8f6-6bc5-11e7-96cc-5fc124fba560.png">

And here's the alternate one:

<img width="1438" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28333330-a1bed7f8-6bc5-11e7-9dfa-6f96a96c9abf.png">

@Fay-Z @AngelaZ0 Please let me know which one you like better!

**Comment by Amyffz** [comment]
@Fay-Z @AngelaZ0  me and ashely talked about using the second one and including 6 boxes in total, one of them being "you" meaning whoever is visiting the site

**Comment by mcdoash** [comment]
It's complete!! I'll add in the "you" box now.
