### ISSUE TITLE
General Responsiveness

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#7]
I haven't even gotten to implementing this yet, so this is more of a to-do than a issue at the moment. I will eventually need help testing the site. I'll update this issue once it's time to do so.

## Main Page
- [x] make sure divs are % not px
- [x] change text to rem instead of px
- [x] insure images resize properly
- [x] set min/max
- [x] use media-queries to allow for viewing across all devices
     - [x] Nav
     - [x] Intro section
     - [x] About section
     - [x] Team section
- [x] test site across multiple devices

### Devices Tested
- [x] Macbook Pro (15-inch, Sierra)
     - [x] Chrome working
     - [x] Safari working
- [x] iPhone 5
     - [x] Safari
          - [x] Portrait working
          - [x] Landscape working

## Weekly Problems Page
- [x] Macbook Pro (15-inch, Sierra)
     - [x] Chrome working
     - [x] Safari working
- [x] iPhone 5
     - [x] Safari
          - [x] Portrait working
          - [x] Landscape working
- [x] iPad (3?)
     - [x] Safari
          - [x] Portrait working
          - [x] Landscape working
     - [x] Chrome
          - [x] Portrait working
          - [x] Landscape working

**Comment by mcdoash** [comment]
Everything is done except for the nav bar (#14)!!! Once it is all merged into the master it would be great if you guys could check them out on whatever devices you have.

**Comment by mcdoash** [comment]
@Fay-Z @Amyffz @AngelaZ0 If you test the website, could you please let me know what devices you used, the orientation(s) (if applicable) and any issues?? Thank you so much!

**Comment by mcdoash** [comment]
# Review: Safari on iPhone 5
## Portrait & Landscape
- ~~title too wide (adds horizontal scroll)~~
- ~~title not positioned properly~~
- ~~header image isn't showing up~~
- ~~nav isn't sticky~~
- ~~nav turns fixed~~
- ~~when you open the navbar it scrolls the body, not the nav~~

**Comment by mcdoash** [comment]
# Things to look for
When testing the site, I'd appreciate it if you could check for the following:
- Everything looks fine on both portrait and landscape (if applicable)
-  If there's horizontal overflow (If you can scroll horizontally)
- Sizing of elements, if they look off in any way
- If you're viewing on a device where the navbar is fully expanded/horizontal:
     - Dropdown on "Resources" link works properly
- If you're viewing on a device where the navbar has to be expanded:
     - General ease of use
     - If when it's expanded and you try to scroll if it scrolls the navbar or the rest of the website
     - The navbar doesn't go up into the header

# Please Include
- Device used (please be specific)
- Browser(s) used (it would be great if you could try any/all you have)
- Window size or orientation if there's a problem

**Comment by mcdoash** [comment]
# Review: Safari on Macbook Pro (15-inch, Mid 2015)
- ~~Sticky nav doesn't work (not supported on Safari?)~~
- ~~Nav turns fixed (again seems to be a Safari problem)~~

**Comment by mcdoash** [comment]
@Fay-Z @Amyffz @AngelaZ0 Could someone with an android phone or tablet tell me if the header background image shows up properly and give me their review in general??? Thanks.

**Comment by Amyffz** [comment]
My phone is an Android
I didn't have problem with header picture
Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 25, 2017, at 12:09 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

@Fay-Z<https://github.com/fay-z> @Amyffz<https://github.com/amyffz> @AngelaZ0<https://github.com/angelaz0> Could someone with an android phone or tablet tell me if the header background image shows up properly and give me their review in general??? Thanks.

**Comment by mcdoash** [comment]
@Amyffz Great, thank you! Pretty sure it's just on apple then. I was also wondering if when in portrait and you expand the navbar and try to scroll, does it scroll the navbar or the rest of the website? Also were you viewing it in chrome or the default browser?

**Comment by Amyffz** [comment]
The landscape works fine however there is some layering issues.

**Comment by mcdoash** [comment]
What kind of layering issues? Also did you check the scroll?

**Edit:** Just fixed the countdown timer layering if that's what you're referring to.

**Comment by mcdoash** [comment]
Just found this seriously awesome feature in Safari that lets you simulate other devices **and** operating systems. If it works I might not need as much help from you guys.

**Edit:** It doesn't seem like it works 100%, since it doesn't replicate the scroll problem I'm encountering on iPhone/iPad. This leads me to believe it might have something to do with tough scrolling?

**Comment by mcdoash** [comment]
Okay, so I *finally* got it to stop scrolling the body. Except now, when you exit the nav it automatically puts you back to the top of the page. Ugh.

**Comment by AngelaZ0** [comment]
the following is what I have so far for resources,



Sources:

www.codeabbey.com/index/task_list

*Practices/tasks range from easy to difficult level (include some hints)

Good for the beginner?

We could select a few tasks as practice and challenges for people in the
club to do

*Suggested Website:*

Codeacademy: http://www.codecademy.com/learn/all

Khan academy: http://www.khanacademy.org/



*Java tutorial:*

 http://docs.oracle.com/javase/tutorial/

https://www.tutorialspoint.com/java/index.htm

·         Array: http://docs.oracle.com/javase/tutorial/java/nutsandbolts/
arrays.html

·         While & do-while statement:

http://docs.oracle.com/javase/tutorial/java/nutsandbolts/while.html

·         For Statement: http://docs.oracle.com/javase/
tutorial/java/nutsandbolts/for.html

·         If statement: http://docs.oracle.com/javase/
tutorial/java/nutsandbolts/if.html

*Contest *

·         CCC 2017 problem, tests, and solution:
https://open.cs.uwaterloo.ca/language-independent-lessons/

·         ECOO-CS Programming Contest: http://ecoocs.org/boardwide.php

*Wed, March 21 - March 28, 2018*



*Extra*

·         Python for beginner: https://cscircles.cemc.uwaterloo.ca/

·         Independent Studying Module: https://open.cs.uwaterloo.ca/
language-independent-lessons/



*Preparation for Contest:*

·         Dramatic Programming

·         Recursion

·         Array, two-dimensional, three-dimensional, etc

·         ArrayList, LinkedList

·         Loop

**Comment by mcdoash** [comment]
@AngelaZ0 that list is awesome!!! Definitely great starting points 👍 it would great to link to these sources from our site.

**Comment by mcdoash** [comment]
Okay, so now it doesn't scroll the background, but if you're viewing it on a device where the nav itself overflows, you can't scroll it, since I disabled *all* scrolling.

**Comment by mcdoash** [comment]
Okay, so I think I've found a solution. Could you guys check your phones in landscape and check if when you open the nav if anything is cut off? I removed the extra categories under Resources, so it should just be the four links. @Amyffz @AngelaZ0 @Fay-Z

**Comment by mcdoash** [comment]
I've noted that the gap between the nav and the "Welcome to CCC" looks really strange—especially on mobile. Should I remove it completely, only on mobile, or keep it how it is?

<img width="1439" alt="central_programming_and_general_responsiveness_ _issue__7_ _centralprogramming_centralprogramming_github_io" src="https://user-images.githubusercontent.com/29292463/28646460-bc01506c-722f-11e7-8472-5a47d30c47e7.png">
<img width="1439" alt="central_programming_and_general_responsiveness_ _issue__7_ _centralprogramming_centralprogramming_github_io" src="https://user-images.githubusercontent.com/29292463/28646467-c6767432-722f-11e7-9278-704102a115f6.png">
<img width="327" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28646491-de1b5760-722f-11e7-9155-0a33932aec36.png">

**Comment by Amyffz** [comment]
I don't think it's a big deal, just leave it

Sent from BlueMail<http://www.bluemail.me/r?b=10215>
On Jul 26, 2017, at 6:26 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

I've noted that the gap between the nav and the "Welcome to CCC" looks really strange—especially on mobile. Should I remove it completely, only on mobile, or keep it how it is?

[central_programming_and_general_responsiveness_ _issue__7_ _centralprogramming_centralprogramming_github_io]<https://user-images.githubusercontent.com/29292463/28646460-bc01506c-722f-11e7-8472-5a47d30c47e7.png>

[central_programming_and_general_responsiveness_ _issue__7_ _centralprogramming_centralprogramming_github_io]<https://user-images.githubusercontent.com/29292463/28646467-c6767432-722f-11e7-9278-704102a115f6.png>

[central_programming]<https://user-images.githubusercontent.com/29292463/28646491-de1b5760-722f-11e7-9155-0a33932aec36.png>

**Comment by mcdoash** [comment]
Well, just made the last page (contact form) responsive, so I think this issue is officially solved.
