### ISSUE TITLE
Website Images

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#8]
All of the images currently in the main page are just placeholders. We discussed putting drawings of ourselves in the team section but I'm not sure that we have any plans for the other photos. If you're looking for one on google, I'd suggest setting size to large and usage rights to "available for reuse".

**Comment by Amyffz** [comment]
kay

**Comment by Amyffz** [comment]
i am 
so 
lost
rn

**Comment by AngelaZ0** [comment]
What is other photos?

**Comment by mcdoash** [comment]
@Amyffz GitHub is really confusing I'm so sorry. If you want you can read [this](https://guides.github.com/introduction/flow/) intro guide but it's kinda long.
@AngelaZ0 If you check the index.html on either the main-page-redesign branch or the alt-team-layout branch I'm referring to every photo that's already there. So the header image and the one in the "about" section.

**Comment by mcdoash** [comment]
What do you think about changing the about section image to this one of Ada Lovelace?

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/29929610-f7882892-8e39-11e7-8eb1-a4e1594122b6.png">

The colours fit surprisingly well. If you didn't know, Ada Lovelace is accredited to be one of the first computer programmers (and there's even a [day about her](https://www.daysoftheyear.com/days/ada-lovelace-day/)).

I'm not really sure what kind of image we're going for here, so this photo might not fit at all.

**Comment by mcdoash** [comment]
Okay, how about this:
When I was typing up the about section it ended up pretty long. I was thinking about adding a link on the end that would swap out the photo and text to a section about why you should learn programming? That way everything fits and the picture of Ada Lovelace would make more sense there?

@Amyffz @AngelaZ0 @Fay-Z

**Comment by Fay-Z** [comment]
Sure, it will be great.

**Comment by mcdoash** [comment]
Ignore the text; I haven't finished writing it yet and a lot of it will be deleted. The gif looks awful when it autoplays but it will look something like this.

![about](https://user-images.githubusercontent.com/29292463/29935564-302768f8-8e4d-11e7-98d0-f876e65ccba2.gif)

**Comment by Fay-Z** [comment]
This looks good to me.

**Comment by mcdoash** [comment]
@Fay-Z Thank You!!

What about this image of central for the about part??

![about](https://user-images.githubusercontent.com/29292463/29936527-91a181ba-8e50-11e7-98cc-d18b9508667f.jpg)
@AngelaZ0 @Amyffz

**Comment by Fay-Z** [comment]
Yeah, this image also works great. Centered on the idea of study
programming in central 👍. I now start to like this image more, but both
are fine. You can decide.

**Comment by Amyffz** [comment]
woah looks great

**Comment by mcdoash** [comment]
@Amyffz thanks!!!

**Comment by mcdoash** [comment]
What does everyone think of the header image?? Feel free to suggest a different one.

**Comment by mcdoash** [comment]
Declaring this closed since no one commented.

**Comment by mcdoash** [comment]
![header-strip](https://user-images.githubusercontent.com/29292463/30512896-52d72182-9ac7-11e7-9295-9b5e6e29e077.png)
